### ISSUE TITLE
Changeling Augmented Eyesight - no night vision

### ISSUE THREAD

**Issue by CosmicScientist** [tgstation/-tg-station#10297]
Server: Sybil

Revision: 2015-06-30 78daa216709836c8aa86de0600b4c3adc98fffdb 

Problem Description: Augmented Eyesight grants thermal vision but not night vision.

What did you expect to happen: To see through the darkness of maintenance and become the biggest murderboner since the previous round.

What happened instead: Thermal vision was there, night vision was also there... for what felt like one or two ticks and then turned off, if I deactivated and reactivated the vision it'd repeat like that, ahelped and got told it was a bug so to wear mesons instead (let's say flashbangs are worse with that combo).

Why is this bad/What are the consequences: I feel hurt and lied to even though I didn't ask the admin for a refund on the point scam.

Steps to reproduce the problem: Become a changeling, evolve augmented eyesight, activate it in a dark place, cry.

Possibly related stuff: It was a normal traitorling round (I didn't have an uplink) and the last thing that apparently fixed this was #9721 @Jordie0608

**Comment by Invisty** [comment]
Yeah, the message you get says "the darkness creeps away" or something. 

Honestly they'd be a lot less OP if they were just NVGs instead of thermals, but this perhaps balance is another issue.

**Comment by Supermichael777** [comment]
someone made them set see invisible without dating night vision. literally a 2 line fix but I'm on phone right now.

**Comment by Supermichael777** [comment]
Setting  night vision

**Comment by Anonus** [comment]
Also, it stays active after respeccing, and you can't turn it off unless you buy it again.

**Comment by francinum** [comment]
Wasn't that fixed as well.

**Comment by xxalpha** [comment]
All of this was fixed, how late are you niggers.

**Comment by CosmicScientist** [comment]
@xxalpha Which PR fixed it then?

**Comment by xxalpha** [comment]
This one https://github.com/tgstation/-tg-station/pull/9721
https://github.com/tgstation/-tg-station/blob/master/code/game/gamemodes/changeling/powers/augmented_eyesight.dm#L19

**Comment by AnturK** [comment]
This is not fixed. See invisible is reset on life, so see_in_dark does absolutely nothing.

**Comment by CosmicScientist** [comment]
@xxalpha read the last line in the OP. I linked to that. This is happening after that was merged on the 3rd of June and the branch closed 15 days a go and AnturK has the reason as to why right I presume.
