### ISSUE TITLE
Multiple brains entering a positronic brain

### ISSUE THREAD

**Issue by Niknakflak** [tgstation/-tg-station#11331]
Witnessed a player who did in this in-game multiple times.
Apparently you get the prompt, wait until someone else takes over the brain and gets placed in a cyborg (or potentially an AI?) and then hit yes to become the brain which shoves you inside the newly made cyborg where the previous player was.  They can talk and such but not interact.

**Comment by Marflowerose** [comment]
So, Legion feature?

**Comment by GunHog** [comment]
I thought I fixed this ;_;

**Comment by SconesC** [comment]
had it happen as well, I fact I think this may be a dupe

**Comment by Shadowlight213** [comment]
Probaby due to the previous mind moving to the borg mob. Posibrain checks for someone in the brain currently I think

**Comment by Incoming5643** [comment]
Right, when an MMI/positronic becomes a cyborg, the brainmob slot is left empty, and can be taken up by someone else if they still have the pop up open.

**Comment by AnonymousNow** [comment]
Still happening.
