### ISSUE TITLE
Beam code doesn't support turfs as origins/targets

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#12850]
Because the code uses .loc checks instead of get_turf if you feed it turfs as start and/or end points the code will actually try to target the area the turfs are in.

---

<s>So I got a report that the beams had gone missing from the lich resurrection spell.

<s>The truth is they're still there... they're just a little confused.

![scrnshot1](https://cloud.githubusercontent.com/assets/4176358/10931798/f0929c9c-8298-11e5-8072-9a02d57fb7b3.png)

<s>The terminal points of that beam are supposed to be the turf over the fallen lich body, and the turf over the pile of bones four tiles due east (ignore the one by the fire extinguisher). The length and angle of the beam is correct, but for some very strange reason every beam is transposed, Usually towards the southwest corner

<s>A recent change is most likely the issue, as this worked locally while I was bugfixing the beam back in #12751. This of course could be my fault, but I'm struggling to see how I could fuck it up like THIS.

<s>Lightning seems to be fine, so I think it's specifically an issue with turf attached beams</s>

**Comment by RemieRichards** [comment]
@Incoming5643 beams work in #12820 which should be merged soon.
but I didn't change much of the main logic, just made it more robust and cheaper.
so... it's your fault?

**Comment by Incoming5643** [comment]
As much as things have been my fault I'm utterly bamboozled how very simple things like get_turf could somehow misrepresent themselves.

**Comment by Incoming5643** [comment]
After further testing I've determined the rogue beam always starts from the most southwestern tile in the current area that isn't dense.

I have no idea why.

**Comment by RemieRichards** [comment]
lol wat.

**Comment by Incoming5643** [comment]
All I can grasp at is that I know that the .loc of a turf is its area, and that THAT fact probably has something to do with this.

**Comment by RemieRichards** [comment]
yes, but why on earth are you reading the loc of a turf?
Is this a holdover from when the beam was originally from an object, and not the turf? (Which iirc was your attempt at fixing the beams just actually disappearing)

**Comment by Incoming5643** [comment]
No part of the the beam generation uses a .loc, and both ends of the bema are fixed to what should be a turf.

There's a loc check in "get_turf" which is like the only place I could see what I sad coming into play... but I mean, what's there to break about get_turf

**Comment by RemieRichards** [comment]
if it was ```get_turf()``` being broken (which it isn't) there'd be a lot more wacky shit going on than just misplaced beams.

**Comment by duncathan** [comment]
there's a loc check in `get_turf()`? I thought it was just `return locate(/turf) in locs`

**Comment by RemieRichards** [comment]
@duncathan it hasn't been that for almost 6 months, maybe longer.
We use a ```get_turf()``` given by Lummox, which when I implemented it was 64% (iirc) faster than what we used at the time.

**Comment by duncathan** [comment]
goes to show how up to date I am

**Comment by Incoming5643** [comment]
body_turf.Beam(item_turf,icon_state="drain_life",icon='icons/effects/effects.dmi',time=10+10*resurrections,maxdistance=INFINITY)

How body_turf works is:

			var/mob/old_body = current_body
			var/turf/body_turf = get_turf(old_body)
			current_body = lich
where current body is set when you get the spell, then updated to the new body afterwards

item_turf:

			var/turf/item_turf = get_turf(marked_item)

where marked_item is just the phylactery, also set only once before any of this code runs. 

---

Again the distance and bearing between these two points is read correctly, it's just in the wrong PLACE.

**Comment by Incoming5643** [comment]
setting body_turf to get_turf(current_body) instead of get_turf(old_body) doesn't fix the problem, nor does substituting get_turf(user)

**Comment by Incoming5643** [comment]
code/datums/beam.dm line 63

var/obj/effect/ebeam/X= new beam_type(origin.loc)

The loc of a turf is an area. So passing any turfs as starting or ending points of beams will cause this issue.

**Comment by RemieRichards** [comment]
```origin.loc``` was almost certainly intended as "the atom's turf" (this is ancient code by Gunbuddy), in which case a single ```get_turf(origin)``` outside of the ```for()``` would solve it (```get_turf()``` on a turf returns the same turf supplied)

**Comment by Incoming5643** [comment]
So it's not my fault it doesn't work, but it is my fault for trusting the rusting code of a dead man. I can live with that.
