### ISSUE TITLE
genetics is ultra fucked

### ISSUE THREAD

**Issue by dannno** [tgstation/-tg-station#6861]
https://tgstation13.org/phpBB/viewtopic.php?f=10&t=2465
everything is broken

**Comment by tkdrg** [comment]
@Razharas

**Comment by Ergovisavi** [comment]
I'm guessing most of this shit is fixed by #6847

**Comment by dannno** [comment]
my worry was that some of this was intentional
like a feature or something

**Comment by Jalleo** [comment]
Is the server updated yet since that PR got merged?

**Comment by Actionb** [comment]
This bug is still in the game...though maybe isn't consistent. Was working genetics for 20 minutes without problems. Then all of the sudden, every second change in the SE resets the blocks.

**Comment by dannno** [comment]
still an enormous issssssueeee

**Comment by Jalleo** [comment]
@Razharas are you still working on fixing this or is it open for anyone to try and fix?

**Comment by dannno** [comment]
THIS IS NOT FIXED AT ALL

**Comment by dannno** [comment]
STILL A HUGE ISSUE 4 REAL BUT EVEN WORSE NOW

>26 blocks
>even with 95% accuracy you still only really have a 25% chance of actually mutating the block you hit and not some other random one
>INJECTING SE's INTO YOU NEVER WORKS AND GIVES YOU A COMPLETELY RANDOM MUTATION

hhhhhhhhhhhhnnnnnnnnnnnnnnnnnnn
